#!/usr/bin/env node
// lib/spec.json → skill/onchainos-lite/references/commands/<top>.md
// Compact, generated command cards: one signature line + one-line purpose + one line per option.
// The full upstream help text is always available via `ocl <command> --help`.
//   node tools/gen-docs.mjs          write files
//   node tools/gen-docs.mjs --check  exit 1 if any file is stale
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILL = join(ROOT, 'skill', 'onchainos-lite');
const OUT = join(SKILL, 'references', 'commands');
const spec = JSON.parse(readFileSync(join(SKILL, 'lib', 'spec.json'), 'utf8'));
// lite-only commands (doctor, auth …) get cards too
const liteNodes = JSON.parse(readFileSync(join(SKILL, 'lib', 'lite-spec.json'), 'utf8')).nodes;
for (const [p, n] of Object.entries(liteNodes)) spec.nodes[p] = { ...n, opts: n.opts || [] };
const CHECK = process.argv.includes('--check');

// Abbreviations whose dot must not end the first sentence ("(e.g. "1000000" …)" used to be cut to "(e.g").
const ABBR = /\b(e\.g|i\.e|etc|vs)\./gi;
// A sentence boundary inside parentheses ("(optional; defaults to …)") is not the end of the sentence.
const balanced = (x) => (x.match(/\(/g) || []).length <= (x.match(/[)\]]/g) || []).length;
const firstSentence = (s) => {
  const t = s.replace(/\s+/g, ' ').trim().replace(ABBR, (a) => a.replace(/\./g, '\u0000'));
  const ends = [...t.matchAll(/[.;](?=\s|$)/g)].map((m) => m.index);
  const cut = [...ends, t.length].find((i) => balanced(t.slice(0, i))) ?? ends[0] ?? t.length;
  const one = t.slice(0, cut).replace(/\u0000/g, '.');
  return one.length > 160 ? one.slice(0, 157) + '…' : one;
};

// Parse "Options:" blocks of the raw clap help into {long -> help text}
function optionHelp(help) {
  const map = {};
  const lines = help.split('\n');
  let cur = null, inOpts = false;
  for (const l of lines) {
    if (/^(Options|Arguments):/.test(l)) { inOpts = true; continue; }
    if (/^\S/.test(l)) { inOpts = false; cur = null; continue; }
    if (!inOpts) continue;
    const m = l.match(/^\s{2,6}(?:-\w,\s+)?(--[\w-]+|<[\w-]+>|\[[\w-]+\])(?:[ =]<[^>]+>)?(?:\.\.\.)?(?:\s{2,}(.*))?$/);
    if (m) { cur = m[1]; map[cur] = (m[2] || '').trim(); continue; }
    if (cur && /^\s{7,}\S/.test(l)) map[cur] += (map[cur] ? ' ' : '') + l.trim();
  }
  return map;
}

function about(help) {
  return help.split('\n\nUsage:')[0].trim();
}

function card(path, node) {
  const oh = optionHelp(node.help);
  const opts = node.opts.filter((o) => !o.global);
  const sig = [`ocl ${path}`];
  for (const a of node.args || []) sig.push(a.required ? `<${a.name}>` : `[${a.name}]`);
  for (const o of opts.filter((o) => o.required)) sig.push(`${o.long} <${o.value}>`);
  const groups = node.requiredGroups || [];
  for (const g of groups) sig.push('(' + g.map((n) => opts.find((o) => o.name === n)).filter(Boolean).map((o) => `${o.long} <${o.value}>`).join(' | ') + ')');
  const optional = opts.filter((o) => !o.required && !groups.flat().includes(o.name));
  if (optional.length) sig.push('[options]');
  const out = [`### ${path}`, firstSentence(about(node.help)) + (node.hidden ? ' _(hidden upstream)_' : ''), '`' + sig.join(' ') + '`'];
  for (const o of optional) {
    const h = (oh[o.long] || '').replace(/\s*\[(default|possible values|aliases?): [^\]]+\]/g, '').trim();
    const extras = [o.default !== undefined ? `default ${o.default}` : '', o.possible ? o.possible.join('|') : ''].filter(Boolean).join('; ');
    out.push(`- \`${o.long}${o.flag ? '' : ` <${o.value}>`}\`${o.multiple ? ' (repeatable)' : ''}${h ? ' — ' + firstSentence(h) : ''}${extras ? ` (${extras})` : ''}`);
  }
  for (const a of node.args || []) {
    const h = oh[`<${a.name}>`] || oh[`[${a.name}]`];
    if (h) out.push(`- \`${a.name}\` — ${firstSentence(h)}`);
  }
  return out.join('\n');
}

const tops = [...new Set(Object.keys(spec.nodes).filter((p) => p).map((p) => p.split(' ')[0]))];
const files = {};
for (const top of tops) {
  const leaves = Object.entries(spec.nodes).filter(([p, n]) => (p === top || p.startsWith(top + ' ')) && !n.subs);
  if (!leaves.length) continue;
  const lite = !!liteNodes[top];
  const source = lite ? 'lib/lite-spec.json (onchainos-lite only)' : `upstream onchainos ${spec.upstream}`;
  const head = `# ${top} — commands\n\n<!-- generated by tools/gen-docs.mjs from ${source}; do not edit -->\n${firstSentence(about(spec.nodes[top].help))}. Required flags are in the signature; \`ocl ${top} <cmd> --help\` prints the full ${lite ? '' : 'upstream '}help.\n`;
  const body = leaves.map(([p, n]) => card(p, n)).join('\n\n') + '\n';
  // Long cards get a one-line contents list so a partial read still shows the whole surface.
  const toc = body.split('\n').length > 100 ? `\nContents (${leaves.length}): ${leaves.map(([p]) => p.slice(top.length + 1) || top).join(' · ')}\n` : '';
  files[`${top}.md`] = head + toc + '\n' + body;
}

let stale = [];
if (!CHECK) mkdirSync(OUT, { recursive: true });
for (const [name, text] of Object.entries(files)) {
  const p = join(OUT, name);
  const cur = existsSync(p) ? readFileSync(p, 'utf8') : null;
  if (cur !== text) { stale.push(name); if (!CHECK) writeFileSync(p, text); }
}
if (existsSync(OUT)) for (const f of readdirSync(OUT)) if (!files[f]) stale.push(`${f} (orphan)`);
if (CHECK) {
  if (stale.length) { console.log(`stale command docs: ${stale.join(', ')} — run node tools/gen-docs.mjs`); process.exit(1); }
} else {
  const total = Object.values(files).reduce((n, t) => n + t.length, 0);
  console.log(`references/commands: ${Object.keys(files).length} files, ${total} chars, ${stale.length} updated`);
}
