// lib/core/qr.mjs — byte parity with upstream cli/src/qr.rs + the qrcode 0.14.1 crate.
// Vectors: test/oracle-qr/vectors.json, generated by the Rust oracle crate in
// test/oracle-qr (exact qrcode 0.14.1 + verbatim upstream render/PNG code, std::path
// Windows flavour, GetFullPathNameW):
//   cd test/oracle-qr && cargo run --release --offline -- vectors.json
// and test/oracle-qr/vectors-paths-unix.json (std's unix path module, via wasm32):
//   cd test/oracle-qr/unix-paths && cargo build --release --offline --target wasm32-unknown-unknown
//   node test/oracle-qr/gen-unix-paths.mjs
// End-to-end against the upstream binary: node test/oracle-qr/e2e-upstream.mjs
import { test, describe, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, mkdirSync, writeFileSync, existsSync, rmSync, statSync, readdirSync, realpathSync } from 'node:fs';
import { join, dirname, sep } from 'node:path';
import { tmpdir, userInfo } from 'node:os';
import { createHash, randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
// config.mjs resolves the state dir at import time: sandbox it before importing.
const SANDBOX = realpathSync(mkdtempSync(join(tmpdir(), 'ocl-qr-test-')));
const HOME = join(SANDBOX, 'home');
process.env.OCL_HOME = HOME;
delete process.env.ONCHAINOS_FUNDING_IMAGE_DIR;
delete process.env.CODEX_THREAD_ID;
const qr = await import('../../skill/onchainos-lite/lib/core/qr.mjs');
const { stringify } = await import('../../skill/onchainos-lite/lib/core/json.mjs');
after(() => rmSync(SANDBOX, { recursive: true, force: true }));

const V = JSON.parse(readFileSync(join(ROOT, 'test', 'oracle-qr', 'vectors.json'), 'utf8'));
const sha = (b) => createHash('sha256').update(b).digest('hex');
const vectorInput = (v) => {
  const prefix = v.input !== undefined ? Buffer.from(v.input, 'utf8') : Buffer.from(v.inputHex, 'hex');
  return v.repeat ? Buffer.concat([prefix, Buffer.alloc(v.repeat[1], v.repeat[0])]) : prefix;
};
const modulesHex = (code) => {
  const bits = Buffer.alloc(Math.ceil(code.colors.length / 8));
  code.colors.forEach((c, i) => { if (c) bits[i >> 3] |= 0x80 >> (i & 7); });
  return bits.toString('hex');
};
const SAMPLE_ADDR = '0x1234567890abcdef1234567890abcdef12345678';
const PNG_NAME = new RegExp(`^onchainos-funding-qr-${process.pid}-\\d{19,}\\.png$`);
const baseName = (p) => p.split(/[\\/]/).pop();
const withEnv = (vars, fn) => {
  const saved = Object.fromEntries(Object.keys(vars).map((k) => [k, process.env[k]]));
  for (const [k, v] of Object.entries(vars)) if (v === undefined) delete process.env[k]; else process.env[k] = v;
  try { return fn(); } finally {
    for (const [k, v] of Object.entries(saved)) if (v === undefined) delete process.env[k]; else process.env[k] = v;
  }
};

describe('qrcode 0.14.1 encoder vs Rust oracle', () => {
  test(`oracle covers every version and the overflow error (${V.qr.length} vectors)`, () => {
    const versions = new Set(V.qr.map((v) => v.version).filter(Boolean));
    for (let v = 1; v <= 40; v++) assert.ok(versions.has(v), `version ${v} covered`);
    assert.ok(V.qr.some((v) => v.error === 'data too long'));
  });

  test('module matrix, version, errors, inverted Dense1x2 block and PNG bytes match for every vector', () => {
    for (const v of V.qr) {
      const data = vectorInput(v);
      if (v.error) {
        assert.throws(() => qr.QrCode.new(data), (e) => e instanceof qr.QrError && e.message === v.error, v.name);
        continue;
      }
      const code = qr.QrCode.new(data);
      assert.equal(code.version, v.version, `${v.name}: version`);
      assert.equal(code.width, v.width, `${v.name}: width`);
      const hex = modulesHex(code);
      if (v.modules) assert.equal(hex, v.modules, `${v.name}: modules`);
      else assert.equal(sha(hex), v.modulesSha256, `${v.name}: modules`);
      const unicode = qr.renderDense1x2Inverted(code);
      if (v.unicode !== undefined) assert.equal(unicode, v.unicode, `${v.name}: unicode`);
      assert.equal(sha(Buffer.from(unicode, 'utf8')), v.unicodeSha256, `${v.name}: unicode`);
      const png = qr.renderGrayscalePng(code);
      assert.equal(png.length, v.pngLen, `${v.name}: png length`);
      assert.equal(sha(png), v.pngSha256, `${v.name}: png bytes`);
    }
  });

  test('render_address_qr_unicode / render_address_qr_png on the named address vectors', () => {
    for (const v of V.qr.filter((x) => !x.name.startsWith('fuzz-') && !x.name.startsWith('boundary-'))) {
      const text = v.input !== undefined && !v.repeat ? v.input : vectorInput(v);
      if (v.error) {
        assert.throws(() => qr.renderAddressQrUnicode(text), { message: v.error });
        assert.throws(() => qr.renderAddressQrPng(text), { message: v.error });
        continue;
      }
      assert.equal(sha(Buffer.from(qr.renderAddressQrUnicode(text), 'utf8')), v.unicodeSha256, v.name);
      assert.equal(sha(qr.renderAddressQrPng(text)), v.pngSha256, v.name);
    }
  });

  test('ISO/IEC 18004 Annex I symbol (crate lib.rs test_annex_i_qr)', () => {
    const code = qr.QrCode.new('01234567');
    const rows = [];
    for (let y = 0; y < code.width; y++) {
      let row = '';
      for (let x = 0; x < code.width; x++) row += code.isDark(x, y) ? '#' : '.';
      rows.push(row);
    }
    assert.deepEqual(rows, [
      '#######..#.##.#######', '#.....#..####.#.....#', '#.###.#.#.....#.###.#', '#.###.#.##....#.###.#',
      '#.###.#.#.###.#.###.#', '#.....#.#...#.#.....#', '#######.#.#.#.#######', '........#..##........',
      '#.#####..#..#.#####..', '...#.#.##.#.#..#.##..', '..#...##.#.#.#..#####', '....#....#.....####..',
      '...######..#.#..#....', '........#.#####..##..', '#######..##.#.##.....', '#.....#.#.#####...#.#',
      '#.###.#.#...#..#.##..', '#.###.#.##..#..#.....', '#.###.#.#.##.#..#.#..', '#.....#........##.##.',
      '#######.####.#..#.#..',
    ]);
  });

  test('segment parser and optimiser (crate optimize.rs tests)', () => {
    const seg = (mode, begin, end) => ({ mode, begin, end });
    const [N, A, B, K] = [0, 1, 2, 3];
    assert.deepEqual(qr.parseSegments(Buffer.from('ABC123abcd')), [seg(A, 0, 3), seg(N, 3, 6), seg(B, 6, 10)]);
    assert.deepEqual(qr.parseSegments(Buffer.from('01049123451234591597033130128%10ABC123')),
      [seg(N, 0, 29), seg(A, 29, 30), seg(N, 30, 32), seg(A, 32, 35), seg(N, 35, 38)]);
    assert.deepEqual(qr.parseSegments(Buffer.from('82a0814141b181f0', 'hex')), [seg(K, 0, 4), seg(A, 4, 5), seg(B, 5, 6), seg(K, 6, 8)]);
    assert.deepEqual(qr.parseSegments(Buffer.from('e38182e3808141efbdb1e284ab', 'hex')),
      [seg(K, 0, 4), seg(B, 4, 5), seg(K, 5, 7), seg(B, 7, 10), seg(K, 10, 12), seg(B, 12, 13)]);
    assert.deepEqual(qr.parseSegments(Buffer.from('8130', 'hex')), [seg(B, 0, 1), seg(N, 1, 2)]);
    assert.deepEqual(qr.parseSegments(Buffer.from('ebc0', 'hex')), [seg(B, 0, 1), seg(B, 1, 2)]);
    assert.deepEqual(qr.parseSegments(Buffer.from('817f', 'hex')), [seg(B, 0, 1), seg(B, 1, 2)]);
    assert.deepEqual(qr.parseSegments(Buffer.from('814081', 'hex')), [seg(K, 0, 2), seg(B, 2, 3)]);
    assert.deepEqual(qr.parseSegments(Buffer.alloc(0)), []);
    assert.deepEqual(qr.optimizeSegments([seg(A, 0, 3), seg(N, 3, 6), seg(B, 6, 10)], 1), [seg(A, 0, 6), seg(B, 6, 10)]);
    assert.deepEqual(qr.optimizeSegments([seg(N, 0, 29), seg(A, 29, 30), seg(N, 30, 32), seg(A, 32, 35), seg(N, 35, 38)], 9),
      [seg(N, 0, 29), seg(A, 29, 38)]);
    assert.deepEqual(qr.optimizeSegments([seg(K, 0, 4), seg(A, 4, 5), seg(B, 5, 6), seg(K, 6, 8)], 1), [seg(B, 0, 8)]);
    assert.deepEqual(qr.optimizeSegments([seg(K, 0, 10), seg(B, 10, 11)], 1), [seg(K, 0, 10), seg(B, 10, 11)]);
  });

  test('generator polynomials equal the ec.rs literal table', () => {
    const literal = {
      7: '57e59295ee6615', 10: 'fb432e3d7646405e202d', 13: '4a98b06456646a6882dace8c4e',
      15: '08b73d5bca25333a3aed8c7c056369', 16: '78686b6d66a14c035bbf93a9b6c2e178',
      17: '2b8bce4e2bef7bced69318639627f3a388', 18: 'd7ea9e5eb86176aa4fbb9894fcb305626099',
      20: '113c4f323da31abbcab4dde153ef9ca4d4d4bcbe', 22: 'd2abf7f25de60e6ddd35c84a08ac6250db86a069a5e7',
      24: 'e5798730d375fb7e9fb4a998c0e2e4da6f0075e85760e315', 26: 'ad7d9e0267b6761191c96f1ca535a115f58e0d6630e39991da46',
      28: 'a8dfc868e0ea6cb46ebec393cd1be8c9152bf5572ac3d477f225097b',
      30: '29ad9198d81fb3b632306e56ef60de7d2aade2c1e0829c25fbd8ee28c0b4',
      68: 'f79fdf21e05d4d465aa020fe2b965465becd85343ccaa5dccb975d540f54fdada059e334c7615fe734b1297d89f1a6e17602362052d7afc62beeeb1b65b87f030508a3ee',
    };
    for (const [n, hex] of Object.entries(literal)) assert.equal(Buffer.from(qr.generatorPolynomial(Number(n))).toString('hex'), hex, `n=${n}`);
  });
});

describe('PNG writer (qr.rs encode_grayscale_png / zlib_store / crc32 / adler32)', () => {
  test('crc32, adler32 and stored-deflate zlib across block boundaries', () => {
    for (const b of V.png.blocks) {
      const data = Buffer.from(Array.from({ length: b.len }, (_, i) => (i * 31 + 7) & 0xff));
      assert.equal(qr.crc32(data), b.crc32, `crc32 len=${b.len}`);
      assert.equal(qr.crc32Table(data), b.crc32, `table crc32 len=${b.len}`);
      const cut = b.len >> 1;
      assert.equal(qr.crc32(data.subarray(cut), qr.crc32(data.subarray(0, cut))), b.crc32, `running crc32 len=${b.len}`);
      assert.equal(qr.crc32Table(data.subarray(cut), qr.crc32Table(data.subarray(0, cut))), b.crc32, `running table crc32 len=${b.len}`);
      assert.equal(qr.adler32(data), b.adler32, `adler32 len=${b.len}`);
      const z = qr.zlibStore(data);
      assert.equal(z.length, b.zlibLen, `zlib len=${b.len}`);
      assert.equal(sha(z), b.zlibSha256, `zlib bytes len=${b.len}`);
    }
    assert.equal(qr.encodeGrayscalePng(2, 1, Buffer.from([0, 0, 255])).toString('hex'), V.png.tinyHex);
  });

  test('chunks carry valid CRCs and a square IHDR (upstream render_address_qr_png_returns_png_bytes)', () => {
    const png = qr.renderAddressQrPng(SAMPLE_ADDR);
    assert.deepEqual([...png.subarray(0, 8)], [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    const kinds = [];
    for (let off = 8; off < png.length;) {
      const len = png.readUInt32BE(off);
      const kind = png.toString('latin1', off + 4, off + 8);
      const end = off + 8 + len;
      assert.equal(png.readUInt32BE(end), qr.crc32(png.subarray(off + 4, end)), `${kind} crc`);
      if (kind === 'IHDR') {
        assert.equal(len, 13);
        assert.equal(png.readUInt32BE(off + 8), png.readUInt32BE(off + 12));
        assert.equal(png.readUInt32BE(off + 8), (qr.QrCode.new(SAMPLE_ADDR).width + 8) * 8);
      }
      kinds.push(kind);
      off = end + 4;
    }
    assert.deepEqual(kinds, ['IHDR', 'IDAT', 'IEND']);
  });

  test('unicode block shape: odd row count, quiet zone, last row of upper halves', () => {
    const block = qr.renderAddressQrUnicode(SAMPLE_ADDR);
    const rows = block.split('\n');
    const size = qr.QrCode.new(SAMPLE_ADDR).width + 8;
    assert.equal(rows.length, (size + 1) / 2);
    for (const r of rows) assert.equal([...r].length, size);
    assert.equal(rows[rows.length - 1], '▀'.repeat(size));
    assert.equal(rows[0], '█'.repeat(size));
    assert.ok(!block.endsWith('\n'));
    assert.notEqual(block, qr.renderAddressQrUnicode(`ethereum:${SAMPLE_ADDR}`));
  });
});

describe('display mode detection', () => {
  test(`Codex session first lines (${V.codexLines.length} oracle vectors: serde_json acceptance, BTreeMap order, str::trim)`, () => {
    for (const c of V.codexLines) assert.equal(qr.displayModeFromCodexSessionLine(c.line), c.mode, JSON.stringify(c.line).slice(0, 100));
  });

  test('upstream codex metadata tests', () => {
    const tui = '{"type":"session_meta","payload":{"originator":"codex-tui","source":"cli"}}';
    assert.equal(qr.displayModeFromCodexSessionLine(tui), 'terminal-unicode');
    for (const source of ['vscode', 'appServer']) {
      assert.equal(qr.displayModeFromCodexSessionLine(`{"type":"session_meta","payload":{"originator":"Codex Desktop","source":"${source}"}}`), 'image-notify');
    }
    assert.equal(qr.displayModeFromCodexMeta(' Codex Desktop ', 'AppServer'), 'image-notify');
    assert.equal(qr.displayModeFromCodexMeta('CODEX-TUI', 'CLI'), 'terminal-unicode');
    assert.equal(qr.displayModeFromCodexSessionLine('not json'), null);
    assert.equal(qr.displayModeFromCodexMeta('unknown', 'unknown'), null);
    assert.equal(qr.displayModeFromCodexMeta(null, null), null);
    assert.equal(qr.displayModeFromCodexSessionLine('{"type":"session_meta","payload":{"originator":"codex_exec","source":"exec"}}'), 'terminal-unicode');
  });

  test('find_json_string walks objects in sorted key order and arrays in order', () => {
    assert.equal(qr.findJsonString({ b: { k: 'B' }, a: { k: 'A' } }, 'k'), 'A');
    assert.equal(qr.findJsonString({ k: 5, z: { k: 'deep' } }, 'k'), 'deep');
    assert.equal(qr.findJsonString([{ x: 1 }, [{ k: 'arr' }]], 'k'), 'arr');
    assert.equal(qr.findJsonString('k', 'k'), null);
    assert.equal(qr.findJsonString({ 'é': { k: 'e-acute' }, z: { k: 'z' } }, 'k'), 'z');   // UTF-8 byte order
  });

  test('str::trim semantics (U+FEFF kept, U+0085 stripped) and ASCII-only lowercase', () => {
    assert.equal(qr.rustTrim('\u0085 x 　'), 'x');
    assert.equal(qr.rustTrim('﻿x'), '﻿x');
    assert.equal(qr.normalizeCodexMetaValue(' CODEX-TUI '), 'codex-tui');
    assert.equal(qr.normalizeCodexMetaValue('İX'), 'İx');
  });

  test('read_first_line keeps the newline and rejects invalid UTF-8', () => {
    const dir = join(SANDBOX, 'lines');
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'a.jsonl'), '{"a":1}\r\n{"b":2}\n');
    writeFileSync(join(dir, 'b.jsonl'), 'no newline');
    writeFileSync(join(dir, 'c.jsonl'), Buffer.from([0x7b, 0xff, 0x7d, 0x0a]));
    writeFileSync(join(dir, 'd.jsonl'), Buffer.concat([Buffer.from('{"source":"cli"}\n'), Buffer.from([0xff])]));
    writeFileSync(join(dir, 'e.jsonl'), '');
    writeFileSync(join(dir, 'f.jsonl'), 'x'.repeat(20000) + '\ntail');
    assert.equal(qr.readFirstLine(join(dir, 'a.jsonl')), '{"a":1}\r\n');
    assert.equal(qr.readFirstLine(join(dir, 'b.jsonl')), 'no newline');
    assert.equal(qr.readFirstLine(join(dir, 'c.jsonl')), null);
    assert.equal(qr.readFirstLine(join(dir, 'd.jsonl')), '{"source":"cli"}\n');
    assert.equal(qr.readFirstLine(join(dir, 'e.jsonl')), '');
    assert.equal(qr.readFirstLine(join(dir, 'f.jsonl')), 'x'.repeat(20000) + '\n');
    assert.equal(qr.readFirstLine(join(dir, 'missing.jsonl')), null);
  });

  test('invalid codex session candidate does not stop search (upstream test)', () => {
    const dir = join(SANDBOX, 'qr_display_mode_sessions');
    mkdirSync(dir, { recursive: true });
    const bad = join(dir, 'bad.jsonl'), good = join(dir, 'good.jsonl');
    writeFileSync(bad, 'not json\n');
    writeFileSync(good, '{"type":"session_meta","payload":{"originator":"codex-tui","source":"cli"}}');
    assert.equal(qr.displayModeFromCodexSessionFiles([bad, join(dir, 'missing.jsonl'), good]), 'terminal-unicode');
    assert.equal(qr.displayModeFromCodexSessionFiles([bad]), null);
  });

  test('find_codex_session_files: recursive, *.json/*.jsonl whose name contains the id', () => {
    const id = randomUUID();
    const root = join(SANDBOX, 'codex-home', 'sessions');
    mkdirSync(join(root, '2026', '09', '28'), { recursive: true });
    mkdirSync(join(root, `dir-${id}.jsonl`), { recursive: true });              // a directory, not a file
    writeFileSync(join(root, '2026', '09', '28', `rollout-${id}.jsonl`), '{"payload":{"originator":"codex_exec"}}\n');
    writeFileSync(join(root, '2026', `meta-${id}.json`), '{"source":"vscode"}\n');
    writeFileSync(join(root, '2026', `other-${id}.txt`), '{"source":"cli"}\n');
    writeFileSync(join(root, 'rollout-unrelated.jsonl'), '{"source":"cli"}\n');
    const found = qr.findCodexSessionFiles(root, id).map((p) => p.slice(root.length + 1)).sort();
    assert.deepEqual(found, [join('2026', '09', '28', `rollout-${id}.jsonl`), join('2026', `meta-${id}.json`)].sort());
    assert.deepEqual(qr.findCodexSessionFiles(join(SANDBOX, 'nope'), id), []);
    const mode = withEnv({ CODEX_THREAD_ID: `  ${id}\n`, CODEX_HOME: join(SANDBOX, 'codex-home') }, () => qr.displayModeFromCodexSession());
    assert.ok(mode === 'terminal-unicode' || mode === 'image-notify');
    const only = join(SANDBOX, 'codex-home-2', 'sessions');
    mkdirSync(only, { recursive: true });
    writeFileSync(join(only, `x-${id}.jsonl`), '{"payload":{"originator":"Codex Desktop"}}\n');
    withEnv({ CODEX_THREAD_ID: id, CODEX_HOME: join(SANDBOX, 'codex-home-2') }, () => {
      assert.equal(qr.displayModeFromCodexSession(), 'image-notify');
      assert.equal(qr.detectDisplayMode(), 'image-notify');
      assert.equal(qr.displayMode(), 'image-notify');
    });
    withEnv({ CODEX_THREAD_ID: '   ', CODEX_HOME: join(SANDBOX, 'codex-home-2') }, () => assert.equal(qr.displayModeFromCodexSession(), null));
    withEnv({ CODEX_THREAD_ID: undefined }, () => assert.equal(qr.displayModeFromCodexSession(), null));
  });

  test('codex session roots: $CODEX_HOME/sessions then dirs::home_dir()/.codex/sessions', () => {
    withEnv({ CODEX_HOME: join(SANDBOX, 'ch') }, () => {
      const roots = qr.codexSessionRoots();
      assert.equal(roots[0], join(SANDBOX, 'ch', 'sessions'));
      assert.equal(roots[1], qr.rustJoin(qr.dirsHomeDir(), '.codex', 'sessions'));
    });
    withEnv({ CODEX_HOME: '' }, () => assert.equal(qr.codexSessionRoots().length, 1));
  });

  test('dirs::home_dir: Windows Known Folder profile (ignores %USERPROFILE%), Unix $HOME unless empty', () => {
    const profile = userInfo().homedir;
    if (process.platform === 'win32') {
      withEnv({ USERPROFILE: join(SANDBOX, 'fake-profile'), HOME: join(SANDBOX, 'fake-home') }, () => assert.equal(qr.dirsHomeDir(), profile));
    } else {
      withEnv({ HOME: '/some/home' }, () => assert.equal(qr.dirsHomeDir(), '/some/home'));
      withEnv({ HOME: '' }, () => assert.equal(qr.dirsHomeDir(), profile || null));
      withEnv({ HOME: undefined }, () => assert.equal(qr.dirsHomeDir(), profile || null));
    }
  });

  test('a session under an overridden %USERPROFILE% is not found (upstream probe codex-home-userprofile-override)', { skip: process.platform !== 'win32' }, () => {
    const id = randomUUID();
    const fake = join(SANDBOX, 'fake-profile-2');
    mkdirSync(join(fake, '.codex', 'sessions'), { recursive: true });
    writeFileSync(join(fake, '.codex', 'sessions', `rollout-${id}.jsonl`), '{"payload":{"originator":"codex-tui"}}\n');
    withEnv({ CODEX_THREAD_ID: id, CODEX_HOME: undefined, USERPROFILE: fake }, () => assert.equal(qr.displayModeFromCodexSession(), null));
  });

  test('Codex roots are read the way Win32 addresses them (`codex.` reaches codex, `codex ` does not)', { skip: process.platform !== 'win32' }, () => {
    const id = randomUUID();
    const codex = join(SANDBOX, 'codex-w32');
    mkdirSync(join(codex, 'sessions'), { recursive: true });
    writeFileSync(join(codex, 'sessions', `r-${id}.jsonl`), '{"payload":{"originator":"codex-tui"}}\n');
    assert.equal(qr.findCodexSessionFiles(`${codex}.\\sessions`, id).length, 1);
    assert.equal(qr.findCodexSessionFiles(`${codex} \\sessions`, id).length, 0);
    assert.equal(qr.findCodexSessionFiles(`\\\\?\\${codex}\\.\\sessions`, id).length, 0);    // NT: "." is an invalid name
    withEnv({ CODEX_THREAD_ID: id, CODEX_HOME: `${codex}.` }, () => assert.equal(qr.displayModeFromCodexSession(), 'terminal-unicode'));
  });

  test('TTY fallback yields one of the two modes', () => {
    withEnv({ CODEX_THREAD_ID: undefined }, () => {
      assert.ok(['terminal-unicode', 'image-notify'].includes(qr.displayModeFromTty()));
      assert.equal(qr.detectDisplayMode(), qr.displayModeFromTty());
    });
  });
});

describe('QrOutput (build_qr_output)', () => {
  test('terminal-unicode populates terminalQr only, struct field order', () => {
    const out = qr.buildQrOutputWithMode(SAMPLE_ADDR, null, 'terminal-unicode');
    assert.equal(out.terminalQr, qr.renderAddressQrUnicode(SAMPLE_ADDR));
    assert.equal(stringify(out), `{"requestedFormat":"auto","resolvedFormat":"unicode","displayMode":"terminal-unicode","terminalQr":${JSON.stringify(out.terminalQr)}}`);
    for (const k of ['imagePath', 'mimeType', 'markdownImage', 'notifyCommandArgs']) assert.equal(out[k], undefined);
  });

  test('image-notify writes the PNG under imageDir and fills the image fields', () => {
    const dir = join(SANDBOX, 'qr_build_output_image');
    const out = qr.buildQrOutputWithMode(SAMPLE_ADDR, dir, 'image-notify');
    assert.equal(out.resolvedFormat, 'png');
    assert.equal(out.terminalQr, undefined);
    assert.ok(out.imagePath.startsWith(dir + sep), out.imagePath);
    assert.match(baseName(out.imagePath), PNG_NAME);
    assert.deepEqual(readFileSync(out.imagePath), qr.renderAddressQrPng(SAMPLE_ADDR));
    assert.equal(out.mimeType, 'image/png');
    assert.equal(out.markdownImage, qr.markdownImageForPath(out.imagePath));
    assert.deepEqual(out.notifyCommandArgs, ['onchainos', 'agent', 'user-notify', '--content', '<localized content>', '--image-path', out.imagePath]);
    assert.equal(stringify(out), `{"requestedFormat":"auto","resolvedFormat":"png","displayMode":"image-notify","imagePath":${JSON.stringify(out.imagePath)},"mimeType":"image/png","markdownImage":${JSON.stringify(out.markdownImage)},"notifyCommandArgs":${JSON.stringify(out.notifyCommandArgs)}}`);
    if (process.platform !== 'win32') assert.equal(statSync(dir).mode & 0o777, 0o700);
  });

  test('encode failure degrades silently to requestedFormat + displayMode', () => {
    const overLong = `0x${'a'.repeat(8000)}`;
    const dir = join(SANDBOX, 'qr_build_output_degrade');
    for (const mode of ['image-notify', 'terminal-unicode']) {
      const out = qr.buildQrOutputWithMode(overLong, dir, mode);
      assert.equal(stringify(out), `{"requestedFormat":"auto","displayMode":"${mode}"}`);
    }
    assert.ok(!existsSync(dir), 'no directory is created when encoding fails');
    assert.throws(() => qr.writeQrPng(overLong, dir), { message: `Failed to encode QR for ${overLong}: data too long` });
  });

  test('build_qr_output resolves the mode from the runtime (Codex metadata here)', () => {
    const id = randomUUID();
    const root = join(SANDBOX, 'codex-home-3', 'sessions');
    mkdirSync(root, { recursive: true });
    writeFileSync(join(root, `${id}.jsonl`), '{"payload":{"originator":"codex-tui"}}\n');
    withEnv({ CODEX_THREAD_ID: id, CODEX_HOME: join(SANDBOX, 'codex-home-3') }, () => {
      const out = qr.buildQrOutput(SAMPLE_ADDR);
      assert.equal(out.displayMode, 'terminal-unicode');
      assert.equal(out.resolvedFormat, 'unicode');
    });
  });

  test('qrOutput builder skips None fields and keeps declaration order', () => {
    const out = qr.qrOutput({ notifyCommandArgs: ['a'], markdownImage: 'm', mimeType: 'image/png', imagePath: 'p', displayMode: 'image-notify', resolvedFormat: null, requestedFormat: 'auto' });
    assert.equal(stringify(out), '{"requestedFormat":"auto","displayMode":"image-notify","imagePath":"p","mimeType":"image/png","markdownImage":"m","notifyCommandArgs":["a"]}');
  });
});

describe('write_qr_png directory priority', () => {
  const blocker = join(SANDBOX, 'blocker-file');
  writeFileSync(blocker, 'x');
  const blocked = join(blocker, 'sub');                     // mkdir under a regular file fails

  test('explicit image_dir wins', () => {
    const dir = join(SANDBOX, 'explicit');
    const p = withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: join(SANDBOX, 'env-dir') }, () => qr.writeQrPng(SAMPLE_ADDR, dir));
    assert.equal(dirname(p), dir);
    assert.match(baseName(p), PNG_NAME);
  });

  test('then $ONCHAINOS_FUNDING_IMAGE_DIR', () => {
    const env = join(SANDBOX, 'env-dir');
    const p = withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: env }, () => qr.writeQrPng(SAMPLE_ADDR, blocked));
    assert.equal(dirname(p), env);
  });

  test('then <home>/tmp/funding-qr', () => {
    const p = withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: blocked }, () => qr.writeQrPng(SAMPLE_ADDR, blocked));
    assert.equal(dirname(p), join(HOME, 'tmp', 'funding-qr'));
  });

  test('then <cwd>/.onchainos/tmp/funding-qr (cwd-relative markdown)', () => {
    rmSync(HOME, { recursive: true, force: true });
    writeFileSync(HOME, 'not a dir');
    const cwd = process.cwd();
    const work = join(SANDBOX, 'work');
    mkdirSync(work, { recursive: true });
    process.chdir(work);
    try {
      const out = withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: undefined }, () => qr.buildQrOutputWithMode(SAMPLE_ADDR, blocked, 'image-notify'));
      assert.equal(dirname(out.imagePath), join(work, '.onchainos', 'tmp', 'funding-qr'));
      const s = sep === '\\' ? '\\' : '/';
      assert.equal(out.markdownImage, `![QR Code](<.${s}.onchainos${s}tmp${s}funding-qr${s}${baseName(out.imagePath)}>)`);
    } finally {
      process.chdir(cwd);
      rmSync(HOME, { force: true });
    }
  });

  test('Win32 addressing: `x.` → x (written), `x ` / `x...` / `x \\b` fail the write and fall through (upstream probes img-win-*)', { skip: process.platform !== 'win32' }, () => {
    const base = join(SANDBOX, 'w32dirs');
    mkdirSync(base, { recursive: true });
    const home = join(HOME, 'tmp', 'funding-qr');
    const run = (leaf) => withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: `${base}\\${leaf}` }, () => qr.writeQrPng(SAMPLE_ADDR));
    const dotted = run('td.');
    assert.equal(dirname(dotted), `${base}\\td.`);                       // the string keeps the dot…
    assert.ok(existsSync(join(base, 'td', baseName(dotted))));            // …the file lands in td
    assert.ok(!readdirSync(base).includes('td.'));
    for (const leaf of ['tsp ', 'tdd...', 'is \\b', 'tds .']) {
      assert.equal(dirname(run(leaf)), home, leaf);
    }
    assert.ok(readdirSync(base).includes('tsp') && readdirSync(base).includes('is'), 'create_dir_all made the normalised directories');
    assert.equal(dirname(run('id.\\b')), `${base}\\id.\\b`);
    assert.ok(existsSync(join(base, 'id', 'b')));
    for (const tail of ['\\\\y', '\\.', '\\..\\y', '/y']) {                // NT rejects these verbatim names
      const dir = `\\\\?\\${base}\\vb${tail}`;
      assert.equal(dirname(withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: dir }, () => qr.writeQrPng(SAMPLE_ADDR))), home, dir);
    }
    const ve = `\\\\?\\${base}\\ve\\\\y`;
    assert.equal(dirname(withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: ve }, () => qr.writeQrPng(SAMPLE_ADDR))), home);
    assert.ok(!readdirSync(base).includes('ve'), 'an empty name fails before any directory is created');
    const vmd = `\\\\?\\${base}\\vmd\\.`;                                 // "not found" first: create_dir_all makes vmd, then fails
    assert.equal(dirname(withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: vmd }, () => qr.writeQrPng(SAMPLE_ADDR))), home);
    assert.ok(readdirSync(base).includes('vmd'));
    const vt = `\\\\?\\${base}\\vt.`;                                     // …but keep a verbatim trailing dot
    assert.equal(dirname(withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: vt }, () => qr.writeQrPng(SAMPLE_ADDR))), vt);
    assert.ok(readdirSync(base).includes('vt.'));
    assert.equal(dirname(withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: '   ' }, () => qr.writeQrPng(SAMPLE_ADDR))), home);
  });

  test('fsPath: the Win32 target of a path', { skip: process.platform !== 'win32' }, () => {
    assert.equal(qr.fsPath('C:\\a\\foo.'), '\\\\?\\C:\\a\\foo');
    assert.equal(qr.fsPath('C:\\a\\foo \\b'), '\\\\?\\C:\\a\\foo \\b');
    assert.equal(qr.fsPath('C:/a//b/../c'), '\\\\?\\C:\\a\\c');
    assert.equal(qr.fsPath('\\\\srv\\sh\\x.'), '\\\\?\\UNC\\srv\\sh\\x');
    assert.equal(qr.fsPath('\\\\?\\C:\\a\\foo.'), '\\\\?\\C:\\a\\foo.');
    assert.equal(qr.fsPath('\\??\\C:\\a'), '\\\\?\\C:\\a');
    assert.equal(qr.fsPath('rel.'), `\\\\?\\${process.cwd()}\\rel`);
    for (const bad of ['\\\\?\\C:\\nope\\\\b', '   ', '']) assert.throws(() => qr.fsPath(bad), { code: 'EINVALIDNAME' }, bad);
    // NT: `.`, `..` and `/` names are invalid once reached; a missing directory before them is "not found"
    for (const tail of ['\\.', '\\..\\b', '\\a/b']) {
      assert.throws(() => qr.fsPath(`\\\\?\\${SANDBOX}${tail}`), { code: 'EINVALIDNAME' }, tail);
      assert.throws(() => qr.fsPath(`\\\\?\\${SANDBOX}\\missing${tail}`), { code: 'ENOENT' }, tail);
    }
  });

  test('env::temp_dir(): GetTempPath2W (TMP, TEMP, USERPROFILE, Windows dir; normalised; blank → "\\0")', { skip: process.platform !== 'win32' }, () => {
    const cwd = process.cwd();
    const t = (env) => withEnv({ TMP: undefined, TEMP: undefined, USERPROFILE: undefined, ...env }, () => qr.rustTempDir());
    assert.equal(t({ TMP: 'C:\\t1', TEMP: 'C:\\t2' }), 'C:\\t1\\');
    assert.equal(t({ TMP: '', TEMP: 'C:\\t2' }), '\0');
    assert.equal(t({ TEMP: '   ' }), '\0');
    assert.equal(t({ TEMP: 'C:\\t2' }), 'C:\\t2\\');
    assert.equal(t({ USERPROFILE: 'C:\\Users\\p' }), 'C:\\Users\\p\\');
    assert.equal(t({ TMP: `C:\\${'x'.repeat(300)}`, TEMP: 'C:\\t2' }), 'C:\\t2\\');
    assert.equal(t({ TMP: `C:\\${'y'.repeat(257)}` }), `C:\\${'y'.repeat(257)}\\`);
    assert.equal(t({ TMP: `C:\\${'y'.repeat(258)}`, TEMP: 'C:\\t2' }), 'C:\\t2\\');
    assert.equal(t({ TMP: 'C:\\a\\foo. .' }), 'C:\\a\\foo\\');
    assert.equal(t({ TMP: 'C:/a/./b/../c/' }), 'C:\\a\\c\\');
    assert.equal(t({ TMP: 'rel\\x' }), `${cwd}\\rel\\x\\`);
    assert.equal(t({ TMP: '  C:\\a  ' }), `${cwd}\\  C:\\a\\`);
    assert.equal(t({ TMP: '\\\\?\\C:\\a\\\\b' }), '\\\\?\\C:\\a\\b\\');
    const sys = withEnv({ SystemRoot: 'C:\\Win' }, () => t({}));
    assert.equal(sys, 'C:\\Win\\');
  });

  test('temp dir "\\0" makes the last candidate fail → degrade (upstream probe img-temp-fallback-temp-var)', { skip: process.platform !== 'win32' }, () => {
    const cwd = process.cwd();
    const work = join(SANDBOX, 'work-temp');
    mkdirSync(work, { recursive: true });
    writeFileSync(join(work, '.onchainos'), 'blocker');
    rmSync(HOME, { recursive: true, force: true });
    writeFileSync(HOME, 'not a dir');
    process.chdir(work);
    try {
      const out = withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: undefined, TMP: '', TEMP: join(SANDBOX, 'unused') }, () => qr.buildQrOutputWithMode(SAMPLE_ADDR, null, 'image-notify'));
      assert.equal(stringify(out), '{"requestedFormat":"auto","displayMode":"image-notify"}');
    } finally {
      process.chdir(cwd);
      rmSync(HOME, { force: true });
    }
  });

  test('empty ONCHAINOS_FUNDING_IMAGE_DIR: Windows writes into cwd, Unix skips it', () => {
    const cwd = process.cwd();
    const work = join(SANDBOX, 'work-empty');
    mkdirSync(work, { recursive: true });
    process.chdir(work);
    try {
      const p = withEnv({ ONCHAINOS_FUNDING_IMAGE_DIR: '' }, () => qr.writeQrPng(SAMPLE_ADDR, blocked));
      if (process.platform === 'win32') {
        assert.match(p, PNG_NAME);                            // relative path, written to cwd
        assert.ok(readdirSync(work).includes(p));
        assert.equal(qr.markdownImageForPath(p), `![QR Code](<.\\${p}>)`);
      } else {
        assert.equal(dirname(p), join(HOME, 'tmp', 'funding-qr'));
      }
    } finally {
      process.chdir(cwd);
    }
  });
});

describe('std::path port vs Rust std, both flavours on any host', () => {
  const U = JSON.parse(readFileSync(join(ROOT, 'test', 'oracle-qr', 'vectors-paths-unix.json'), 'utf8'));
  const cj = (c) => (c.t === 'prefix' ? ['prefix', c.p.kind, c.raw, c.p.a, c.p.b] : c.t === 'normal' ? ['normal', c.v] : [c.t]);
  const flavours = [['windows', true, V.pathOpsWinPaths, V.pathOpsWinPairs], ['unix', false, U.paths, U.pairs]];
  for (const [name, win, paths, pairs] of flavours) {
    const P = qr.rustPathFor(win);
    test(`${name}: components (both directions), as_path, parent, has_root / is_absolute — ${paths.length} paths`, () => {
      assert.ok(paths.length > 500);
      for (const v of paths) {
        const at = JSON.stringify(v.p);
        assert.deepEqual(P.components(v.p).map(cj), v.comps, `components ${at}`);
        const it = P.iter(v.p), rev = [];
        for (let c = it.nextBack(); c; c = it.nextBack()) rev.push(cj(c));
        assert.deepEqual(rev, v.rev, `rev ${at}`);
        assert.equal(P.iter(v.p).asPath(), v.asPath, `as_path ${at}`);
        const n = P.iter(v.p); n.next();
        assert.equal(n.asPath(), v.asPathAfterNext, `as_path after next ${at}`);
        const b = P.iter(v.p); b.nextBack();
        assert.equal(b.asPath(), v.asPathAfterBack, `as_path after next_back ${at}`);
        assert.equal(P.parent(v.p), v.parent, `parent ${at}`);
        assert.equal(P.hasRoot(v.p), v.hasRoot, `has_root ${at}`);
        // unix is_absolute == has_root (the wasm32 oracle cannot report it; see unix-paths/lib.rs)
        assert.equal(P.isAbsolute(v.p), win ? v.abs : v.hasRoot, `is_absolute ${at}`);
      }
    });
    test(`${name}: strip_prefix and PathBuf::join — ${pairs.length} pairs`, () => {
      assert.ok(pairs.length > 1000);
      for (const v of pairs) {
        assert.equal(P.stripPrefix(v.a, v.b), v.strip, `strip_prefix ${JSON.stringify([v.a, v.b])}`);
        assert.equal(P.join(v.a, v.b), v.join, `join ${JSON.stringify([v.a, v.b])}`);
      }
    });
  }

  test(`GetFullPathNameW normalisation — ${V.fullPath.length} vectors from the real API`, () => {
    assert.ok(V.fullPath.length > 1000);
    for (const v of V.fullPath) assert.equal(qr.win32FullPath(v.path, v.cwd), v.out, JSON.stringify(v.path));
    // X:rel on another drive uses the per-drive directory (`=X:`) when known
    assert.equal(qr.win32FullPath('Q:rel', 'C:\\w', (d) => (d === 'Q' ? 'Q:\\cur' : undefined)), 'Q:\\cur\\rel');
  });
});

describe('Rust std path semantics used in output strings', () => {
  const platform = process.platform === 'win32' ? 'windows' : 'unix';

  test(`oracle PathBuf::join / markdown_image_for_path vectors (${V.paths.platform})`, { skip: V.paths.platform !== platform }, () => {
    for (const j of V.paths.join) assert.equal(qr.rustJoin(j.base, j.part), j.out, JSON.stringify(j));
    for (const m of V.paths.markdown) assert.equal(qr.markdownImageForPathIn(m.path, m.cwd ?? undefined), m.out, JSON.stringify(m));
  });

  test('unix flavour join / strip_prefix / markdown (hand-derived from std::path, any host)', () => {
    const P = qr.rustPathFor(false);
    assert.equal(P.join('', 'tmp'), 'tmp');
    assert.equal(P.join('/', 'tmp'), '/tmp');
    assert.equal(P.join('/a', 'tmp', 'funding-qr'), '/a/tmp/funding-qr');
    assert.equal(P.join('/a/', 'tmp'), '/a/tmp');
    assert.equal(P.join('/a//b', 'x'), '/a//b/x');
    assert.equal(P.join('a\\', 'x'), 'a\\/x');
    assert.equal(P.join('/a', '/abs'), '/abs');
    const md = (p, cwd) => qr.markdownImageForPathIn(p, cwd, P);
    const f = '/home/u/w/.onchainos/tmp/funding-qr/f.png';
    assert.equal(md(f, '/home/u/w'), '![QR Code](<./.onchainos/tmp/funding-qr/f.png>)');
    assert.equal(md(f, '/home/u/w/'), '![QR Code](<./.onchainos/tmp/funding-qr/f.png>)');
    assert.equal(md(f, '/'), '![QR Code](<./home/u/w/.onchainos/tmp/funding-qr/f.png>)');
    assert.equal(md(f, undefined), `![QR Code](<${f}>)`);
    assert.equal(md('/home/u/wx/f.png', '/home/u/w'), '![QR Code](</home/u/wx/f.png>)');
    assert.equal(md('/home/u/W/f.png', '/home/u/w'), '![QR Code](</home/u/W/f.png>)');
    assert.equal(md('/home/u/w//a/f.png', '/home/u/w'), '![QR Code](<./a/f.png>)');
    assert.equal(md('/home/u/w/./a/f.png', '/home/u/w'), '![QR Code](<./a/f.png>)');
    assert.equal(md('/home/u/w/../w/f.png', '/home/u/w'), '![QR Code](<./../w/f.png>)');
    assert.equal(md('/home/u/w', '/home/u/w'), '![QR Code](<./>)');
    assert.equal(md('rel/f.png', '/home/u/w'), '![QR Code](<./rel/f.png>)');
    assert.equal(md('f.png', undefined), '![QR Code](<./f.png>)');
    assert.equal(md('/home/u/w/a>b/f>.png', '/home/u/w'), '![QR Code](<./a%3Eb/f%3E.png>)');
    assert.equal(P.isAbsolute('/x'), true);
    assert.equal(P.isAbsolute('x/y'), false);
  });

  test('temp dir fallback is absolute and joinable', () => {
    const t = qr.rustTempDir();
    assert.ok(qr.rustIsAbsolute(t) || t === '', t);
    assert.ok(qr.rustJoin(t, 'x.png').endsWith('x.png'));
  });
});
